/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bank_systems_v1;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author river
 */
public class Frame extends javax.swing.JFrame {
    INFO A = new INFO();
    CRUD_OP B= new CRUD_OP();
    int counter;
    
    public Frame() {
        initComponents();
        setupGlassPane();
        jTextField11.setVisible(false);
        jButton6.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel23 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jPanel17.setVisible(false);
        jPanel18 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jPanel15 = new javax.swing.JPanel();
        jPanel15.setVisible(false);
        jPanel16 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jPanel12.setVisible(false);
        jLabel12 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 1280, 720));
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 1280, 720));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 720));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(1280, 720));
        jPanel1.setMinimumSize(new java.awt.Dimension(1280, 720));
        jPanel1.setLayout(null);

        jPanel20.setBackground(new java.awt.Color(255, 0, 0));
        jPanel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel20MouseClicked(evt);
            }
        });

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menu (2).png"))); // NOI18N

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel20);
        jPanel20.setBounds(0, 0, 100, 100);

        jPanel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel19MouseExited(evt);
            }
        });
        jPanel19.setLayout(null);

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo.png"))); // NOI18N
        jPanel19.add(jLabel24);
        jLabel24.setBounds(-20, 10, 290, 220);

        jPanel21.setBackground(new java.awt.Color(0, 0, 255));
        jPanel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel21MouseClicked(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 51));
        jLabel25.setText("TRANSACTION");

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel21Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE))
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
        );

        jPanel19.add(jPanel21);
        jPanel21.setBounds(40, 290, 190, 90);

        jPanel22.setBackground(new java.awt.Color(255, 255, 51));
        jPanel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel22MouseClicked(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 0, 51));
        jLabel26.setText("LOGS");

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel22Layout.createSequentialGroup()
                .addGap(0, 64, Short.MAX_VALUE)
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        jPanel19.add(jPanel22);
        jPanel22.setBounds(40, 440, 190, 100);

        jPanel1.add(jPanel19);
        jPanel19.setBounds(0, 0, 0, 0);

        jPanel3.setBackground(new Color(255,255,255,128));
        jPanel3.setLayout(null);

        jPanel5.setBackground(new Color(255,255,255,128));
        jPanel5.setLayout(null);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Account ID", "First Name", "Last Name", "Account Type", "Balance"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setResizable(false);
            jTable2.getColumnModel().getColumn(1).setResizable(false);
            jTable2.getColumnModel().getColumn(2).setResizable(false);
            jTable2.getColumnModel().getColumn(3).setResizable(false);
            jTable2.getColumnModel().getColumn(4).setResizable(false);
        }

        jPanel5.add(jScrollPane2);
        jScrollPane2.setBounds(0, 0, 1060, 1000);

        jPanel3.add(jPanel5);
        jPanel5.setBounds(0, 40, 1060, 290);

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 51));
        jLabel23.setText("Search:");
        jPanel3.add(jLabel23);
        jLabel23.setBounds(30, 0, 70, 40);

        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField11);
        jTextField11.setBounds(90, 0, 130, 40);

        jButton6.setText("Ok");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton6);
        jButton6.setBounds(240, 10, 76, 30);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(130, 370, 1060, 330);

        jPanel4.setBackground(new Color(255,255,255,180));
        jPanel4.setLayout(null);

        jPanel17.setBackground(new java.awt.Color(204, 255, 204));

        jPanel18.setBackground(new java.awt.Color(255, 255, 255));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 51));
        jLabel20.setText("Account Name:");

        jTextField8.setEditable(false);
        jTextField8.setForeground(new java.awt.Color(0, 0, 51));
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 51));
        jLabel21.setText("Account Type:");

        jTextField9.setForeground(new java.awt.Color(0, 0, 51));
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel18Layout.createSequentialGroup()
                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel18Layout.createSequentialGroup()
                        .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21))
                        .addGap(72, 72, 72))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel18Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(74, 74, 74))))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 51));
        jLabel22.setText("BALANCE:");

        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });

        jButton5.setText("Ok");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                        .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                        .addComponent(jButton5)
                        .addGap(105, 105, 105))))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel17);
        jPanel17.setBounds(370, 0, 343, 223);

        jPanel15.setBackground(new java.awt.Color(204, 255, 204));

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));

        jLabel16.setBackground(new java.awt.Color(204, 204, 204));
        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 51));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 51));
        jLabel19.setText("Account name");

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(78, 78, 78))))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 51));
        jLabel17.setText("Account Type:");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Savings", "Current" }));
        jComboBox2.setSelectedIndex(-1);

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 51));
        jLabel18.setText("Balance:");

        jButton4.setText("Ok");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                        .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14))
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(100, 100, 100))
        );

        jPanel4.add(jPanel15);
        jPanel15.setBounds(290, 10, 400, 210);

        jPanel12.setBackground(new java.awt.Color(204, 255, 204));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 51));
        jLabel12.setText("Account ID");
        jLabel12.setOpaque(true);

        jTextField5.setBackground(new java.awt.Color(255, 255, 255));
        jTextField5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jTextField5.setOpaque(true);

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setForeground(new java.awt.Color(0, 0, 51));
        jButton3.setText("Ok");
        jButton3.setOpaque(true);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(101, Short.MAX_VALUE)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel12)
                    .addComponent(jTextField5)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(104, 104, 104))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel12);
        jPanel12.setBounds(340, 20, 290, 130);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 52));
        jLabel2.setText("First Name: ");
        jPanel4.add(jLabel2);
        jLabel2.setBounds(70, 40, 110, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 51));
        jLabel3.setText("Last Name:");
        jPanel4.add(jLabel3);
        jLabel3.setBounds(70, 90, 90, 30);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 51));
        jLabel4.setText("Email:");
        jPanel4.add(jLabel4);
        jLabel4.setBounds(110, 140, 50, 30);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 51));
        jLabel5.setText("Phone Number:");
        jPanel4.add(jLabel5);
        jLabel5.setBounds(470, 40, 120, 30);

        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel4.add(jTextField1);
        jTextField1.setBounds(160, 40, 250, 30);

        jTextField2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPanel4.add(jTextField2);
        jTextField2.setBounds(160, 90, 250, 32);

        jTextField3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPanel4.add(jTextField3);
        jTextField3.setBounds(160, 140, 250, 32);

        jTextField4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jPanel4.add(jTextField4);
        jTextField4.setBounds(590, 40, 250, 30);

        jButton2.setText("Ok");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2);
        jButton2.setBounds(430, 190, 100, 27);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 51));
        jLabel6.setText("Account Type:");
        jPanel4.add(jLabel6);
        jLabel6.setBounds(480, 90, 110, 30);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 51));
        jLabel7.setText("Balance:");
        jPanel4.add(jLabel7);
        jLabel7.setBounds(520, 140, 70, 30);

        jTextField6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPanel4.add(jTextField6);
        jTextField6.setBounds(590, 140, 250, 32);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Current", "Savings", " " }));
        jComboBox1.setSelectedIndex(-1);
        jPanel4.add(jComboBox1);
        jComboBox1.setBounds(590, 90, 180, 30);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(280, 110, 910, 240);

        jPanel6.setBackground(new Color(255,255,255,200));
        jPanel6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.black, new Color(255,255,255,180), java.awt.Color.black, new Color(255,255,255,180)));
        jPanel6.setLayout(null);

        jPanel10.setBackground(new java.awt.Color(51, 51, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("ADD CUSTOMER");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        jPanel6.add(jPanel10);
        jPanel10.setBounds(10, 10, 120, 30);

        jPanel8.setBackground(new java.awt.Color(204, 204, 204));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel8MouseClicked(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 51));
        jLabel10.setText("DEL CUST.");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 21, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel6.add(jPanel8);
        jPanel8.setBounds(10, 120, 120, 30);

        jPanel9.setBackground(new java.awt.Color(204, 204, 204));
        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel9MouseClicked(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 51));
        jLabel11.setText("VIEW ALL");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(0, 15, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        jPanel6.add(jPanel9);
        jPanel9.setBounds(10, 200, 120, 30);

        jPanel7.setBackground(new java.awt.Color(204, 204, 204));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel7MouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 51));
        jLabel9.setText("UP. CUSTOMER");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        jPanel6.add(jPanel7);
        jPanel7.setBounds(10, 80, 120, 30);

        jPanel13.setBackground(new java.awt.Color(204, 204, 204));
        jPanel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel13MouseClicked(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 51));
        jLabel8.setText("ADD ACCOUNT");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel6.add(jPanel13);
        jPanel13.setBounds(10, 40, 120, 26);

        jPanel14.setBackground(new java.awt.Color(204, 204, 204));
        jPanel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel14MouseClicked(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 51));
        jLabel15.setText("DEL ACCT.");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addGap(0, 21, Short.MAX_VALUE)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        jPanel6.add(jPanel14);
        jPanel14.setBounds(10, 150, 120, 30);

        jPanel1.add(jPanel6);
        jPanel6.setBounds(130, 110, 140, 240);

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setBackground(java.awt.Color.red);
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("X");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(1206, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel11);
        jPanel11.setBounds(0, 0, 1280, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1280, 720);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1280, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void setupGlassPane() {
    // Create a custom Glass Pane that knows how to "punch holes" for your menus
    javax.swing.JPanel customGlassPane = new javax.swing.JPanel() {
        @Override
        public boolean contains(int x, int y) {
            // Check if jPanel12 is visible and the mouse is over it
            if (jPanel12.isVisible()) {
                java.awt.Point p = javax.swing.SwingUtilities.convertPoint(this, x, y, jPanel12);
                if (jPanel12.contains(p)) return false; // RETURN FALSE means "Let the click pass through perfectly"
            }
            // Check jPanel15
            if (jPanel15.isVisible()) {
                java.awt.Point p = javax.swing.SwingUtilities.convertPoint(this, x, y, jPanel15);
                if (jPanel15.contains(p)) return false; 
            }
            // Check jPanel17
            if (jPanel17.isVisible()) {
                java.awt.Point p = javax.swing.SwingUtilities.convertPoint(this, x, y, jPanel17);
                if (jPanel17.contains(p)) return false; 
            }
            
            // If the mouse is ANYWHERE ELSE, return true to block the click!
            return true; 
        }
    };

    customGlassPane.setOpaque(false); // Keep the shield invisible
    
    // Add a basic listener to catch the blocked clicks and beep
    customGlassPane.addMouseListener(new java.awt.event.MouseAdapter() {
        @Override
        public void mousePressed(java.awt.event.MouseEvent e) {
            java.awt.Toolkit.getDefaultToolkit().beep(); 
        }
    });

    // Apply this custom shield to your main window
    this.setGlassPane(customGlassPane);
}

// Now your lock method is incredibly simple and clean
private void setWindowLocked(boolean locked) {
    this.getGlassPane().setVisible(locked);
}
private void closePanelAnimation(javax.swing.JPanel panel, java.awt.event.MouseEvent evt) {
    // 1. Safety Check: Did the mouse actually leave the panel's outer bounds?
    // (This stops it from closing if you hover over a button inside the panel)
    java.awt.Point p = evt.getPoint();
    if (p.x >= 0 && p.x < panel.getWidth() && p.y >= 0 && p.y < panel.getHeight()) {
        return; // Mouse is still safely inside, do nothing!
    }

    // 2. The Reverse Animation Timer
    javax.swing.Timer closeTimer = new javax.swing.Timer(33, new java.awt.event.ActionListener() {
        
        // Grab the panel's current size dynamically
        int currentWidth = panel.getWidth();
        int currentHeight = panel.getHeight();
        
        final int widthSpeed = 100; 
        final int heightSpeed = 140; 

        @Override
        public void actionPerformed(java.awt.event.ActionEvent e) {
            
            // Phase 1: Shrink the WIDTH first
            if (currentWidth > 0) {
                currentWidth -= widthSpeed;
                if (currentWidth < 0) currentWidth = 0; // Clamp to 0
            } 
            // Phase 2: Once width is 0, shrink the HEIGHT
            else if (currentHeight > 0) {
                currentHeight -= heightSpeed;
                if (currentHeight < 0) currentHeight = 0; // Clamp to 0
            } 
            // Phase 3: Animation is finished
            else {
                ((javax.swing.Timer) e.getSource()).stop();
                panel.setVisible(false); // Hide it
            }

            // Apply the shrinking bounds back to the specific panel
            panel.setBounds(0, 0, currentWidth, currentHeight);
            panel.revalidate();
            panel.repaint();
        }
    });
    
    closeTimer.start();
    jPanel20.setVisible(true);
    jPanel20.revalidate();
    jPanel20.repaint();
}
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String input1 = jTextField1.getText();
        String input2 = jTextField2.getText();
        String input3 = jTextField3.getText();
        String input4 = jTextField4.getText();
        if (counter == 1) {
            if (input1 != null && !input1.trim().isEmpty()
                    && input2 != null && !input2.trim().isEmpty()
                    && input3 != null && !input3.trim().isEmpty()
                    && input4 != null && !input4.trim().isEmpty()) {
                if (input1.matches("^[a-zA-Z\\s]+$")) {
                    if (input2.matches("^[a-zA-Z\\s]+$")) {
                        if (input4.matches("^[0-9]+$")) {
                            A.setFname(input1);
                            A.setLname(input2);
                            A.setEmail(input3);
                            A.setPnumber(input4);
                            jTextField1.setText("");
                            jTextField2.setText("");
                            jTextField3.setText("");
                            jTextField4.setText("");
                            B.setCounter(1);
                            B.updAcc(A);
                            jPanel7.setBackground(new Color(204,204,204));
                            jLabel9.setForeground(new Color(0,0,51));
                            jPanel10.setBackground(new Color(51,51,255));
                            jLabel13.setForeground(new Color(255,255,255));
                            JOptionPane.showMessageDialog(this,
                            "Successfully updated",
                            " ",
                            JOptionPane.INFORMATION_MESSAGE);
                             jComboBox1.setVisible(true);
                             jTextField6.setVisible(true);
                             jLabel6.setVisible(true);
                             jLabel7.setVisible(true);
                        } else {
                            JOptionPane.showMessageDialog(this,
                                    "Please enter a valid number (e.g., 3, or 3.5).",
                                    "Invalid Input",
                                    JOptionPane.ERROR_MESSAGE);
                        }
                    } else {
                        JOptionPane.showMessageDialog(this,
                                "Please enter letters only. Numbers and special characters are not allowed.",
                                "Invalid Input",
                                JOptionPane.ERROR_MESSAGE);
                    }

                } else {
                    JOptionPane.showMessageDialog(this,
                            "Please enter letters only. Numbers and special characters are not allowed.",
                            "Invalid Input",
                            JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this,
                        "This field cannot be empty.",
                        "Empty Field",
                        JOptionPane.WARNING_MESSAGE);
            }
        }
        if (counter == 0) {
            String input5 = (String) jComboBox1.getSelectedItem();
            String input6 = jTextField6.getText();
        if (input1 != null && !input1.trim().isEmpty()) {
            if (input2 != null && !input2.trim().isEmpty()) {
                if (input3 != null && !input3.trim().isEmpty()) {
                    if (input4 != null && !input4.trim().isEmpty()) {
                        if (input5 != null && !input5.trim().isEmpty()) {
                            if (input6 != null && !input6.trim().isEmpty()) {
                                if (input1.matches("^[a-zA-Z\\s]+$")) {
                                    if (input2.matches("^[a-zA-Z\\s]+$")) {
                                        if (input4.matches("^[0-9]+$")) {
                                            if (input5.matches("^[a-zA-Z\\s]+$")) {
                                                try {
                                                    double Value2 = Double.parseDouble(input6.trim());
                                                        A.setFname(input1);
                                                        A.setLname(input2);
                                                        A.setEmail(input3);
                                                        A.setPnumber(input4);
                                                        A.setAcctype(input5);
                                                        A.setBalance(Value2);
                                                        B.addAcc(A);
                                                        jTextField1.setText("");
                                                        jTextField2.setText("");
                                                        jTextField3.setText("");
                                                        jTextField4.setText("");
                                                        jComboBox1.setSelectedIndex(-1);
                                                        jTextField6.setText(""); 
                                                } catch (NumberFormatException e) {
                                                    JOptionPane.showMessageDialog(this,
                                                            "Please enter a valid number (e.g., 3, or 3.5).",
                                                            "Invalid Input",
                                                            JOptionPane.ERROR_MESSAGE);
                                                }
                                            } else {
                                                JOptionPane.showMessageDialog(this,
                                                        "Please enter letters only. Numbers and special characters are not allowed.",
                                                        "Invalid Input",
                                                        JOptionPane.ERROR_MESSAGE);
                                            }
                                        } else {
                                            JOptionPane.showMessageDialog(this,
                                                    "Please enter a valid number (e.g., 3, or 3.5).",
                                                    "Invalid Input",
                                                    JOptionPane.ERROR_MESSAGE);
                                        }
                                    } else {
                                        JOptionPane.showMessageDialog(this,
                                                "Please enter letters only. Numbers and special characters are not allowed.",
                                                "Invalid Input",
                                                JOptionPane.ERROR_MESSAGE);
                                    }

                                } else {
                                    JOptionPane.showMessageDialog(this,
                                            "Please enter letters only. Numbers and special characters are not allowed.",
                                            "Invalid Input",
                                            JOptionPane.ERROR_MESSAGE);
                                }

                            } else {
                                JOptionPane.showMessageDialog(this,
                                        "This field cannot be empty.",
                                        "Empty Field",
                                        JOptionPane.WARNING_MESSAGE);
                            }

                        } else {
                            JOptionPane.showMessageDialog(this,
                                    "This field cannot be empty.",
                                    "Empty Field",
                                    JOptionPane.WARNING_MESSAGE);
                        }
                    } else {
                        JOptionPane.showMessageDialog(this,
                                "This field cannot be empty.",
                                "Empty Field",
                                JOptionPane.WARNING_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(this,
                            "This field cannot be empty.",
                            "Empty Field",
                            JOptionPane.WARNING_MESSAGE);
                }

            } else {
                JOptionPane.showMessageDialog(this,
                        "This field cannot be empty.",
                        "Empty Field",
                        JOptionPane.WARNING_MESSAGE);
            }

        } else {
            JOptionPane.showMessageDialog(this,
                    "This field cannot be empty.",
                    "Empty Field",
                    JOptionPane.WARNING_MESSAGE);
        }
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jPanel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseClicked
        jPanel10.setBackground(new Color(204,204,204));
        jLabel13.setForeground(new Color(0,0,51));
        jPanel7.setBackground(new Color(51,51,255));
        jLabel9.setForeground(new Color(255,255,255));
        jLabel12.setText("Customer ID");
        jPanel12.setVisible(true);
        setWindowLocked(true);
        counter = 2;
    }//GEN-LAST:event_jPanel7MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        String searchInput = jTextField5.getText();

    if (searchInput != null && !searchInput.trim().isEmpty()) {
        if (searchInput.matches("^[0-9]+$")) {
            try (Connection conn = DBConnection.getConnection()) {
                String Sql = "SELECT * FROM banking_system.`customer Table` WHERE `Customer ID` = ?"; 
                String Sql2 = "SELECT * FROM banking_system.`account table` WHERE `Acount ID` = ?";
                
                // Using try-with-resources to ensure statements close automatically
                try (PreparedStatement stmt = conn.prepareStatement(Sql);
                     PreparedStatement stmt2 = conn.prepareStatement(Sql2)) {
                    
                    int input = Integer.parseInt(searchInput);

                    switch (counter) {
                        case 0:
                            stmt2.setInt(1, input);
                            try (ResultSet rs2 = stmt2.executeQuery()) {
                                if (rs2.next()) {
                                    int ID = rs2.getInt("Customer Table_Customer ID");
                                    A.setID(ID);
                                    stmt.setInt(1, ID);
                                    try (ResultSet rs = stmt.executeQuery()) {
                                        if (rs.next()) {
                                            jLabel16.setText(rs.getString("First Name") + " " + rs.getString("Last Name"));
                                            jPanel12.setVisible(false);
                                            setWindowLocked(false);
                                            jPanel15.setVisible(true);
                                            setWindowLocked(true);
                                            
                                        } else {
                                            JOptionPane.showMessageDialog(this, "Critical Error: Account exists but no owner found.");
                                        }
                                    }
                                } else {
                                    JOptionPane.showMessageDialog(this, "Account ID " + input + " does not exist.", "Not Found", JOptionPane.ERROR_MESSAGE);
                                    jTextField5.setText("");
                                    jTextField5.requestFocus();
                                }
                            }
                            break;

                        case 1:
                            counter = 0;
                            stmt2.setInt(1, input);
                            A.setID(input);
                            try (ResultSet rs3 = stmt2.executeQuery()) {
                                if (rs3.next()) {
                                    int ID = rs3.getInt("Customer Table_Customer ID");
                                    stmt.setInt(1, ID);
                                    try (ResultSet rs = stmt.executeQuery()) {
                                        if (rs.next()) {
                                            jTextField1.setText(rs.getString("First Name"));
                                            jTextField2.setText(rs.getString("Last Name"));
                                            jTextField3.setText(rs.getString("Email"));
                                            jTextField4.setText(rs.getString("Phone Number"));
                                            jComboBox1.setSelectedItem(rs3.getString("Account Type"));
                                            jTextField6.setText(String.valueOf(rs3.getDouble("Balance")));
                                            
                                            counter++;
                                            jPanel10.setBackground(new Color(51,51,255));
                                            jLabel8.setForeground(new Color(255,255,255));
                                            jPanel7.setBackground(new Color(204,204,204));
                                            jLabel9.setForeground(new Color(0,0,51));
                                            jPanel12.setVisible(false);
                                            setWindowLocked(false);
                                        } else {
                                            JOptionPane.showMessageDialog(this, "The customer linked to this account no longer exists.", "Integrity Error", JOptionPane.ERROR_MESSAGE);
                                        }
                                    }
                                } else { 
                                    JOptionPane.showMessageDialog(this, "Account ID " + input + " not found.", "Search Error", JOptionPane.WARNING_MESSAGE);
                                    jTextField5.setText("");
                                    jTextField5.requestFocus();
                                }
                            }
                            break;

                        case 2:
                            stmt.setInt(1, input);
                            A.setID(input);
                            try (ResultSet rs = stmt.executeQuery()) {
                                if (rs.next()) { 
                                     counter = 1;
                                     jTextField1.setText(rs.getString("First Name"));
                                     jTextField2.setText(rs.getString("Last Name"));
                                     jTextField3.setText(rs.getString("Email"));
                                     jTextField4.setText(rs.getString("Phone Number"));
                                     jComboBox1.setVisible(false);
                                     jTextField6.setVisible(false);
                                     jLabel6.setVisible(false);
                                     jLabel7.setVisible(false);
                                     jPanel12.setVisible(false);
                                     setWindowLocked(false);
                                     jLabel12.setText("Account ID");
                                } else {
                                    JOptionPane.showMessageDialog(this, "Customer ID " + input + " was not found.", "Search Failed", JOptionPane.WARNING_MESSAGE);
                                    jTextField5.setText("");
                                    jTextField5.requestFocus();
                                }
                            }
                            break;

                        case 3: 
                            stmt2.setInt(1, input);
                            try (ResultSet rs4 = stmt2.executeQuery()) {
                                if (rs4.next()) {
                                    int ID = rs4.getInt("Customer Table_Customer ID");
                                    A.setID(input);
                                    jTextField9.setText(rs4.getString("Account Type"));
                                    stmt.setInt(1, ID);
                                    try (ResultSet rs5 = stmt.executeQuery()) {
                                        if (rs5.next()) {
                                            jTextField8.setText(rs5.getString("First Name") + " " + rs5.getString("Last Name"));
                                            jPanel12.setVisible(false);
                                            setWindowLocked(false);
                                            jLabel12.setText("Account ID");
                                            jPanel17.setVisible(true);
                                            setWindowLocked(true);
                                            counter = 0; // Reset only on success
                                        } else {
                                            JOptionPane.showMessageDialog(this, "Critical Error: This account has no linked owner.");
                                        }
                                    }
                                } else {
                                    JOptionPane.showMessageDialog(this, "Search Failed: Account ID " + input + " does not exist.", "Invalid Account", JOptionPane.WARNING_MESSAGE);
                                    jTextField5.setText("");
                                    jTextField5.requestFocus();
                                }
                            }
                            break;
                            case 4:
                            // --- DELETE CUSTOMER & ALL THEIR LINKED ACCOUNTS ---
                            stmt.setInt(1, input);
                            try (ResultSet rs6 = stmt.executeQuery()) {
                                if (rs6.next()) {
                                    // Confirm deletion action with the user
                                    int confirm = JOptionPane.showConfirmDialog(this, 
                                            "Are you sure you want to delete Customer: " + rs6.getString("First Name") + " " + rs6.getString("Last Name") + " and all their active banking accounts?", 
                                            "Confirm Complete Deletion", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
                                    
                                    if (confirm == JOptionPane.YES_OPTION) {
                                        // This sets the counter context inside your delete logic (Function 1)
                                        // keeping counter inside 1 or 2 triggers the customer delete logic
                                        this.counter = 1; 
                                        B.deleteAcc(input);
                                        JOptionPane.showMessageDialog(this, "Customer record and accounts deleted successfully.");
                                        jPanel8.setBackground(new Color(204,204,204));
                                        jLabel10.setForeground(new Color(0,0,51));
                                        jPanel10.setBackground(new Color(51,51,255));
                                        jLabel13.setForeground(new Color(255,255,255));
                                        jPanel12.setVisible(false);
                                        setWindowLocked(false);
                                    }
                                } else {
                                    JOptionPane.showMessageDialog(this, "Deletion Failed: Customer ID " + input + " does not exist.", "Not Found", JOptionPane.WARNING_MESSAGE);
                                    jTextField5.setText("");
                                    jTextField5.requestFocus();
                                    jPanel8.setBackground(new Color(204,204,204));
                                    jLabel10.setForeground(new Color(0,0,51));
                                    jPanel10.setBackground(new Color(51,51,255));
                                    jLabel13.setForeground(new Color(255,255,255));
                                }
                                jLabel12.setText("Account ID");
                            }
                            break;

                        case 5:
                            // --- DELETE A SPECIFIC ACCOUNT ID ONLY ---
                            stmt2.setInt(1, input);
                            try (ResultSet rs7 = stmt2.executeQuery()) {
                                if (rs7.next()) {
                                    int confirm = JOptionPane.showConfirmDialog(this, 
                                            "Are you sure you want to permanently delete Account ID: " + input + " (" + rs7.getString("Account Type") + ")?", 
                                            "Confirm Account Deletion", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
                                    
                                    if (confirm == JOptionPane.YES_OPTION) {
                                        // This sets the counter context inside your delete logic (Function 2)
                                        // setting counter to 0 or 3 triggers single account deletion mode
                                        this.counter = 0; 
                                        B.setCounter(1);
                                        B.deleteAcc(input);
                                        JOptionPane.showMessageDialog(this, "Account deleted successfully.");
                                        jPanel14.setBackground(new Color(204,204,204));
                                        jLabel15.setForeground(new Color(0,0,51));
                                        jPanel10.setBackground(new Color(51,51,255));
                                        jLabel13.setForeground(new Color(255,255,255));
                                        jPanel12.setVisible(false);
                                        setWindowLocked(false);
                                    }
                                } else {
                                    JOptionPane.showMessageDialog(this, "Deletion Failed: Account ID " + input + " does not exist.", "Not Found", JOptionPane.WARNING_MESSAGE);
                                    jTextField5.setText("");
                                    jTextField5.requestFocus();
                                    jPanel14.setBackground(new Color(204,204,204));
                                    jLabel15.setForeground(new Color(0,0,51));
                                    jPanel10.setBackground(new Color(51,51,255));
                                    jLabel13.setForeground(new Color(255,255,255));
                                }
                            }
                            break;
                    } 
                    jTextField5.setText("");
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Database Error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else { 
            JOptionPane.showMessageDialog(this, "Please enter numbers only.");
        }
    }        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jPanel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel13MouseClicked
        jPanel10.setBackground(new Color(204,204,204));
        jLabel13.setForeground(new Color(0,0,51));
        jPanel13.setBackground(new Color(51,51,255));
        jLabel8.setForeground(new Color(255,255,255));
        setWindowLocked(true);
        jPanel12.setVisible(true);
        
    }//GEN-LAST:event_jPanel13MouseClicked

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String input = jTextField10.getText();
         if (input != null && !input.trim().isEmpty()) {
             if (input.matches("^[0-9]+$")) { 
                try (Connection conn = DBConnection.getConnection()) {
                    String Sql2 = "SELECT * FROM banking_system.`account table` WHERE `Acount ID` = ?";
                    PreparedStatement stmt = conn.prepareStatement(Sql2);
                    stmt.setInt(1, A.getID());
                    ResultSet rs = stmt.executeQuery();
                       if (rs.next()) {
                       double balance = rs.getDouble("Balance");
                       double finalbal = Double.parseDouble(input) + balance;
                       A.setBalance(finalbal);
                       B.updAcc(A);
                       jLabel4.setForeground(new Color(0,0,51));
                       jPanel10.setBackground(new Color(51,51,255));
                       jLabel13.setForeground(new Color(255,255,255));
                       jPanel17.setVisible(false);
                       setWindowLocked(false);
                       } else {
                // Missing Else 1: Account ID in object 'A' doesn't exist in DB
                JOptionPane.showMessageDialog(this, "Error: Account record not found.", "Database Error", JOptionPane.ERROR_MESSAGE);}
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(this, "Database Error!", "Error", JOptionPane.ERROR_MESSAGE);}
         } else {
        // Missing Else 2: Input contains letters or symbols
        JOptionPane.showMessageDialog(this, "Please enter a valid numeric amount.", "Invalid Input", JOptionPane.WARNING_MESSAGE);
        jTextField10.setText("");
        jTextField10.requestFocus();
    }} else {
    // Missing Else 3: Input is completely empty
    JOptionPane.showMessageDialog(this, "Amount field cannot be empty.", "Input Required", JOptionPane.WARNING_MESSAGE);
    jTextField10.requestFocus();
}
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String input = (String)jComboBox2.getSelectedItem();
        String input2 = jTextField7.getText();
        if (input != null && !input.trim().isEmpty() && input2 != null && !input2.trim().isEmpty()) {
            if (input2.matches("^[0-9]+$")) {
                try {
                    double Value = Double.parseDouble(input2.trim());
                    A.setAcctype(input);
                    A.setBalance(Value);
                    B.setCounter(1);
                    B.addAcc(A);
                    jComboBox2.setSelectedIndex(-1);
                    jTextField7.setText(" ");
                    jLabel16.setText(" ");
                    jPanel13.setBackground(new Color(204,204,204));
                    jLabel8.setForeground(new Color(0,0,51));
                    jPanel10.setBackground(new Color(51,51,255));
                    jLabel13.setForeground(new Color(255,255,255));
                    jPanel15.setVisible(false);
                    setWindowLocked(false);
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(this,
                        "Please enter a valid number (e.g., 3, or 3.5).",
                        "Invalid Input",
                        JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this,
                    "Please enter letters only. Numbers and special characters are not allowed.",
                    "Invalid Input",
                    JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this,
                "This field cannot be empty.",
                "Empty Field",
                JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jPanel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseClicked
        jPanel10.setBackground(new Color(204,204,204));
        jLabel13.setForeground(new Color(0,0,51));
        jPanel8.setBackground(new Color(51,51,255));
        jLabel10.setForeground(new Color(255,255,255));
        jLabel12.setText("Customer ID");
        jPanel12.setVisible(true);
        setWindowLocked(true);
        counter = 4;
    }//GEN-LAST:event_jPanel8MouseClicked

    private void jPanel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel14MouseClicked
        jPanel10.setBackground(new Color(204,204,204));
        jLabel13.setForeground(new Color(0,0,51));
        jPanel14.setBackground(new Color(51,51,255));
        jLabel15.setForeground(new Color(255,255,255));
        jPanel12.setVisible(true);
        setWindowLocked(true);
        counter = 5;
    }//GEN-LAST:event_jPanel14MouseClicked

    private void jPanel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MouseClicked
    jPanel9.setBackground(new Color(51, 51, 255));
    jLabel11.setForeground(new Color(255, 255, 255));
    jTextField11.setVisible(true);
    jButton6.setVisible(true);
    jTextField11.revalidate();
    jTextField11.repaint();
    jButton6.revalidate();
    jButton6.repaint();
    jPanel1.revalidate();
    jPanel1.repaint();
    jPanel12.setVisible(false);
    jPanel15.setVisible(false);
    jPanel17.setVisible(false);
    DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable2.getModel();
    model.setRowCount(0);
    List<INFO> accountList = B.getAllAccounts(1);
    for (INFO info : accountList) {
        Object[] rowData = {
            info.getID(),      
            info.getFname(),    
            info.getLname(),    
            info.getAcctype(),  
            info.getBalance()   
        };
        model.addRow(rowData);
    }

    }//GEN-LAST:event_jPanel9MouseClicked

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        String searchKeyword = jTextField11.getText().trim();

    // Check if the search bar is empty
    if (searchKeyword.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter a name or Account ID to search.", "Input Required", JOptionPane.WARNING_MESSAGE);
        jTextField11.requestFocus();
        return;
    }

    // Get your pre-configured table model and clear existing records
    javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable2.getModel();
    model.setRowCount(0);

    // SQL query linking accounts and customers, filtering by ID, First Name, or Last Name
    String sql = "SELECT a.`Acount ID`, a.`Account Type`, a.`Balance`, c.`First Name`, c.`Last Name` " +
                 "FROM banking_system.`account table` a " +
                 "INNER JOIN banking_system.`customer table` c " +
                 "ON a.`Customer Table_Customer ID` = c.`Customer ID` " +
                 "WHERE a.`Acount ID` LIKE ? OR c.`First Name` LIKE ? OR c.`Last Name` LIKE ?";

    try (Connection conn = DBConnection.getConnection();
         PreparedStatement stmt = conn.prepareStatement(sql)) {
        
        // Using wildcards (%) so it matches partial text (e.g., "John" matches "Johnathan")
        String matchPattern = "%" + searchKeyword + "%";
        stmt.setString(1, matchPattern);
        stmt.setString(2, matchPattern);
        stmt.setString(3, matchPattern);

        try (ResultSet rs = stmt.executeQuery()) {
            boolean recordsFound = false;
            
            while (rs.next()) {
                recordsFound = true;
                Object[] rowData = {
                    rs.getInt("Acount ID"),
                    rs.getString("First Name"),
                    rs.getString("Last Name"),
                    rs.getString("Account Type"),
                    rs.getDouble("Balance")
                };
                model.addRow(rowData);
            }
            
            // If nothing matched, let the user know
            if (!recordsFound) {
                JOptionPane.showMessageDialog(this, "No matching accounts or customers found.", "Search Results", JOptionPane.INFORMATION_MESSAGE);
            }
        }
        
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Database Error during search: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jPanel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel20MouseClicked
       jPanel20.setVisible(false);
        jPanel19.setBounds(0, 0, 2, 0);
jPanel19.setVisible(true);

// 33ms delay gives roughly 30 FPS
javax.swing.Timer timer = new javax.swing.Timer(33, new java.awt.event.ActionListener() {
    
    // Track our current sizes (start width at 2 so we can see the line drop)
    int currentWidth = 2;
    int currentHeight = 0;
    
    // Set your final targets
    final int targetWidth = 270;
    final int targetHeight = 720;
    
    // Set the speed (pixels to add per frame)
    final int widthSpeed = 100; 
    final int heightSpeed = 140; 

    @Override
    public void actionPerformed(java.awt.event.ActionEvent e) {
        
        // Phase 1: Expand the HEIGHT first (from 0 to 720)
        if (currentHeight < targetHeight) {
            currentHeight += heightSpeed;
            
            // If we overshoot, clamp it perfectly to 720
            if (currentHeight > targetHeight) {
                currentHeight = targetHeight;
            }
        } 
        // Phase 2: Once height is done, expand the WIDTH (from 2 to 270)
        else if (currentWidth < targetWidth) {
            currentWidth += widthSpeed;
            
            // If we overshoot the target, clamp it perfectly to 270
            if (currentWidth > targetWidth) {
                currentWidth = targetWidth;
            }
        } 
        // Phase 3: Animation is completely finished
        else {
            // Stop the timer
            ((javax.swing.Timer) e.getSource()).stop();
        }

        // Apply the new bounds to the panel for this frame
        jPanel19.setBounds(0, 0, currentWidth, currentHeight);
        
        // Refresh the panel so the visual changes appear immediately
        jPanel19.revalidate();
        jPanel19.repaint();
    }
});
jPanel19.getParent().setComponentZOrder(jPanel19, 0);
jPanel19.getParent().repaint();
// Start the animation
timer.start();
    }//GEN-LAST:event_jPanel20MouseClicked

    private void jPanel19MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel19MouseExited
        closePanelAnimation(jPanel19, evt);
    }//GEN-LAST:event_jPanel19MouseExited

    private void jPanel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel21MouseClicked
        transaction myTransactionWindow = new transaction();

        // 2. Tell it to switch to "card2" BEFORE it appears on screen
        myTransactionWindow.switchCard("card2");

        // 3. Use your MainClass to cleanly dispose of the current frame and show the new one
        Bank_Systems_v1.switchWindow(this, myTransactionWindow);
    }//GEN-LAST:event_jPanel21MouseClicked

    private void jPanel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel22MouseClicked
    transaction myTransactionWindow = new transaction();
    myTransactionWindow.viewAllTransactions();
    myTransactionWindow.switchCard("card3");
    Bank_Systems_v1.switchWindow(this, myTransactionWindow);
    }//GEN-LAST:event_jPanel22MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
