-- MySQL Script generated by MySQL Workbench
-- Wed Jun 10 18:46:44 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema Banking_System
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Banking_System
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Banking_System` ;
USE `Banking_System` ;

-- -----------------------------------------------------
-- Table `Banking_System`.`Customer Table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Banking_System`.`Customer Table` (
  `Customer ID` INT NOT NULL AUTO_INCREMENT,
  `First Name` VARCHAR(45) NOT NULL,
  `Last Name` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Phone Number` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`Customer ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Banking_System`.`Account Table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Banking_System`.`Account Table` (
  `Acount ID` INT NOT NULL AUTO_INCREMENT,
  `Customer Table_Customer ID` INT NOT NULL,
  `Account Type` VARCHAR(45) NOT NULL,
  `Balance` DECIMAL(15,2) NOT NULL,
  PRIMARY KEY (`Acount ID`),
  INDEX `fk_Account Table_Customer Table_idx` (`Customer Table_Customer ID` ASC) VISIBLE,
  CONSTRAINT `fk_Account Table_Customer Table`
    FOREIGN KEY (`Customer Table_Customer ID`)
    REFERENCES `Banking_System`.`Customer Table` (`Customer ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Banking_System`.`Transaction Table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Banking_System`.`Transaction Table` (
  `Transaction ID` INT NOT NULL AUTO_INCREMENT,
  `Account Table_Acount ID` INT NOT NULL,
  `Transaction Type` VARCHAR(45) NOT NULL,
  `Amount` DECIMAL(15,2) NOT NULL,
  `Transaction Date` DATE NOT NULL,
  PRIMARY KEY (`Transaction ID`),
  INDEX `fk_Transaction Table_Account Table1_idx` (`Account Table_Acount ID` ASC) VISIBLE,
  CONSTRAINT `fk_Transaction Table_Account Table1`
    FOREIGN KEY (`Account Table_Acount ID`)
    REFERENCES `Banking_System`.`Account Table` (`Acount ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
